//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbtest.Map
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public bool VotedInWeek { get; set; }
        public Nullable<System.DateTime> DateVoted { get; set; }
        public int Votes { get; set; }
    }
}
